### ISSUE TITLE
List of assets is not filled

### ISSUE THREAD

**Issue by tiero** [vulpemventures/dex.vulpem.com#12]
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/3596602/145199453-a185eb84-e49b-4250-b24d-a1331f013577.png">

**Comment by bordalix** [comment]
So, after some investigation, this happens because sometimes proxy.tdex.network takes a long time to respond. And while it not responds, the list of tradable assets is not available.

I'm not sure on how to proceed with this:

1. Should we give it a default set of coins that could be changed after the response from tdex?
2. Or should we add a loading message while the tdex don't respond?

I'm voting for 2, what do you think?

cc @tiero @louisinger

**Comment by tiero** [comment]
We have the same issues on TDEX Mobile App indeed https://github.com/tdex-network/tdex-app/issues/457

I do think adding a modal that pop-up with a loader/spinner and a timeout (ie. 45-60secs?) to asks user to wait and eventually if ALL of them are not responding communicate it to the user.
